### ISSUE TITLE
awkeard.array module not found on importing uproot_methods

### ISSUE THREAD

**Issue by will-fawcett** [scikit-hep/uproot3-methods#96]
I recently installed uproot and uproot_methods:
```
conda config --add channels conda-forge  
conda install uproot
conda install uproot-methods
```

When trying to import uproot_methods I get the following error message:

```
python
>>> import uproot
>>> import awkward
>>> import uproot_methods
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usera/wfawcett/software/miniconda3/lib/python3.8/site-packages/uproot_methods/__init__.py", line 5, in <module>
    from uproot_methods.classes.TVector2 import TVector2, TVector2Array
  File "/usera/wfawcett/software/miniconda3/lib/python3.8/site-packages/uproot_methods/classes/TVector2.py", line 8, in <module>
    import awkward.array.jagged
ModuleNotFoundError: No module named 'awkward.array'
```

Note that I am using
```
>>> awkward.__version__
'1.1.2'
>>> uproot.__version__
'4.0.4'
```
as well as Python 3.8.6

My apologies if this isn't the right use of this tool.

**Comment by will-fawcett** [comment]
After writing this I realised that uproot_methods is for uproot v3 ... this should probably be closed. My apologies.
